// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnkedyucvknvzrkvogog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhua2VkeXVjdmtudnpya3ZvZ29nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDc1OTEsImV4cCI6MjA2NTU4MzU5MX0.vd7dHv2A70g7pFFRhUwJgl-ykt4VylfKocVV7TUb9Jg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);